name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OPENWEATHERMAP_APPID: ${{ secrets.OPENWEATHERMAP_APPID }}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm test
      - run: pnpm build
